## Практическое задание. Часть 1

In [25]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

**нет, количество столбцов В должно быть таким же как количество строк А**

    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

**да, 2х3**

    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

**да, 8х8**

    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

**да, 4х4**

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

$ A + B = 
\begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}
$

In [3]:
a+b

array([[ 5, -3],
       [ 3,  5]])

$
A \cdot B =
\begin{pmatrix}
4 & -1 - 10 \\
12 & -3
\end{pmatrix}
=
\begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$

In [4]:
a.dot(b)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$
3A - 2B + 4C = 
\begin{pmatrix}
3 & 21 \\
9 & -18
\end{pmatrix}
-
\begin{pmatrix}
0 & 10 \\
4 & -2
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix}
=
$

$
\begin{pmatrix}
3 & 11 \\
5 & -16
\end{pmatrix}
+
\begin{pmatrix}
8 & -16 \\
4 & 4
\end{pmatrix}
=
\begin{pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}
$

In [5]:
a = np.matrix([[1, 7], [3, -6]])
b = np.matrix([[0, 5], [2, -1]])
c = np.matrix([[2, -4],[1, 1]])

In [6]:
3*a - 2*b + 4*c

matrix([[ 11,  -5],
        [  9, -12]])

    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$
\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} =
$

$
\begin{pmatrix}
16 + 1 & 20 -2 & 8 + 3 \\
20 - 2 & 25 + 4 & 10 -6 \\
8 + 3 & 10 - 6 & 4 + 9
\end{pmatrix}
= 
\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}
$

In [7]:
a = np.matrix([[4, 1], [5, -2], [2, 3]])

In [8]:
a.dot(a.T)

matrix([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]])

$
\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
 =
$

$
\begin{pmatrix}
16 + 25 + 4 & 4 -10 + 6 \\
4 - 10 + 6 & 1 + 4 + 9
\end{pmatrix} = 
\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}
$

In [9]:
a.T.dot(a)

matrix([[45,  0],
        [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
a = [[4, 1], [5, -2], [2, 3]]
b = [[4, 5, 2], [1, -2, 3]]

In [21]:
def func(a: list, b: list):
    rows = len(a)
    cols = len(b[0])
    c = []
    if rows != cols:
        print('Operation not supported')
    for i in range(rows):
        c.append([0]*cols)
        for j in range(cols):
            tmp = 0
            for k in range(len(a[0])):
                tmp += a[i][k]*b[k][j]
            c[i][j] = tmp
    return c

In [31]:
c = func(a, b)
np.matrix(c)

matrix([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]])

In [32]:
c = func(b, a)
np.matrix(c)

matrix([[45,  0],
        [ 0, 14]])

## Практическое задание. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$
\Delta = sin^2(x) + cos^2(x) = 1
$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$\Delta = 4 \cdot 5 \cdot 9 = 180$

In [34]:
np.linalg.det(np.matrix([[4,2,3],[0,5,1],[0,0,9]]))

180.0

    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\Delta = 5*9 + 2*6*7 + 3*4*8 - 5*7*3 - 2*4*9 - 6*8 = $

In [37]:
45 + 12*7 + 12*8 - 15*7 - 72 - 48

0

In [36]:
np.linalg.det(np.matrix([[1,2,3],[4,5,6],[7,8,9]]))

6.66133814775094e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

$det(A^2) = 16 $

    
   б) $det(A^{T})$;

$detA^T = detA = 4$

    
   в) $det(2A)$.

$det(2A) = 2^n \cdot 4$

   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

**строки 1 и 2 линейно зависимые (2я = -2 первых)**

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

**строки 1 и 3 линейно зависимые. Ранг равен 2**

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**если ко второй строке прибавим первую, получим такую же строку как 3я. Ранг равен 3**