## Практическое задание. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$
\begin{vmatrix}
1 & 1 & -1 & -2 & 0 \\
2 & 1 & -1 & 1 & -2 \\
1 & 1 & -3 & 1 & 4
\end{vmatrix}
$

$
\begin{vmatrix}
1 & 1 & -1 & -2 & 0 \\
0 & -1 & 1 & 5 & -2 \\
0 & 0 & -2 & 3 & 4
\end{vmatrix}
$

$
\begin{vmatrix}
1 & 1 & -1 & -2 & 0 \\
0 & -1 & 1 & 5 & -2 \\
0 & 0 & 1 & -3/2 & -2
\end{vmatrix}
$

$x_3 = \frac{3x_4}{2} - 2$

$x_2 = \frac{3x_4}{2} - 2 + 5x_4 + 2 = \frac{13x_4}{2}$

$x_1 = -\frac{13x_4}{2} + \frac{3x_4}{2} - 2 + 2x_4 = -3x_4 - 2$

$x_4 = R$

частное решение:

пусть $x_4 = 0$, тогда $x_1 = -2, x_2 = 0, x_3 = -2$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$
\begin{vmatrix}
3 & -1 & 1 & 4 \\ 2 & -5 & -3 & -17 \\ 1 & 1& -1 & 0
\end{vmatrix}
$

In [1]:
import numpy as np

In [2]:
a = np.matrix([[3, -1, 1],[2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
a_ext = np.column_stack([a, b])
np.linalg.matrix_rank(a), np.linalg.matrix_rank(a_ext)

(3, 3)

$rankA = rank{\tilde A} = n = 3 =>$ система имеет единственное решение

    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [3]:
a = np.matrix([[2, -4, 6],[1, -2, 3], [3, 6, 9]])
b = np.array([1, -2, 5])
a_ext = np.column_stack([a, b])
np.linalg.matrix_rank(a), np.linalg.matrix_rank(a_ext)

(2, 3)

система несовестна, т.к. $rankA = 2 < rank{\tilde A} = 3$

    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [4]:
a = np.matrix([[1, 2, 5],[3, 1, -8]])
b = np.array([4, -2])
a_ext = np.column_stack([a, b])
np.linalg.matrix_rank(a), np.linalg.matrix_rank(a_ext)

(2, 2)

система имеет бесконечное число решений, т.к. $rank A = rank {\tilde A} = 2 < n = 3$

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [5]:
a = np.matrix([[1,3, -2, 4], [0, 5,0,1],[0,0,3,0],[0,0,0,2]])
b = np.array([3,2,4,1])
a_ext = np.column_stack([a,b])

In [6]:
np.linalg.matrix_rank(a), np.linalg.matrix_rank(a_ext)

(4, 4)

__система имеет единственное решение, т.к.__ $rank A = rank{\tilde A} = 4 = n$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}$

$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2(b-2a)
\end{matrix}
\end{pmatrix}$

__система будет несовместной, если есть такие__ $c-3b+a != 0$

## Практическое задание. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$
detA = 
\begin{vmatrix}
1 & -2 \\ 3 & -4
\end{vmatrix} = -4 + 6 = 2
$

$
detA_1 = 
\begin{vmatrix}
1 & -2 \\ 7 & -4
\end{vmatrix} = -4 + 14 = 10
$

$
detA_2 = 
\begin{vmatrix}
1 & 1 \\ 3 & 7
\end{vmatrix} = 7 - 3 = 4
$

$x_1 = 10/2 = 5 \\ x_2 = 4/2 = 2$

    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$
detA = 
\begin{vmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}
$

$
detA_1 = 
\begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix}
$

$
detA_2 = 
\begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix}
$

$
detA+3 = 
\begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix}
$

In [10]:
detA = (2 + 6 + 20) - 10 + 24 + 1
detA

43

In [11]:
detA1 = 10 + 3 - 40 - 5 - 2 + 120
detA1

86

In [12]:
detA2 = -4 - 60 + 5 + 20 - 10 + 6
detA2

-43

In [13]:
detA3 = 2 + 4 + 40 - 20 + 16 + 1
detA3

43

$x_1 = 86/43 = 2 \\ x_2 = -1 \\ x_3 = 1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$
U =
\begin{vmatrix}
1 & 2 & 4 \\
2 & 9 & 12 \\
3 & 26 & 30
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
l_{21} & 1 & 0 \\
l_{31} & l_{32} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
1 & 2 & 4 \\
0 & 5 & 4 \\
0 & 20 & 18
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & l_{32} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
1 & 2 & 4 \\
0 & 5 & 4 \\
0 & 0 & 2
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 4 & 1
\end{vmatrix}
$

In [18]:
u = np.matrix([[1, 2, 4],[0, 5, 4],[0, 0, 2]])
l = np.matrix([[1, 0, 0],[2, 1, 0],[3, 4, 1]])
np.dot(l, u)

matrix([[ 1,  2,  4],
        [ 2,  9, 12],
        [ 3, 26, 30]])

    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$
U =
\begin{vmatrix}
1 & 1 & 2 & 4 \\
2 & 5 & 8 & 9 \\
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 & 0 \\
l_{21} & 1 & 0 & 0 \\
l_{31} & l_{32} & 1 & 0 \\
l_{41} & l_{42} & l_{43} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
1 & 1 & 2 & 4 \\
0 & 3 & 4 & 1 \\
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 \\
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
1 & 1 & 2 & 4 \\
0 & 3 & 4 & 1 \\
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 \\
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
1 & 1 & 2 & 4 \\
0 & 3 & 4 & 1 \\
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 \\
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{vmatrix}
$

In [19]:
u = np.matrix([[1,1,2,4],[0,3,4,1],[0,0,3,1],[0,0,0,4]])
l = np.matrix([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]])

In [20]:
np.dot(l,u)

matrix([[ 1,  1,  2,  4],
        [ 2,  5,  8,  9],
        [ 3, 18, 29, 18],
        [ 4, 22, 53, 33]])

    
__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$
U =
\begin{vmatrix}
2 & 1 & 3 \\
11 & 7 & 5 \\
9 & 8 & 4
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
l_{21} & 1 & 0 \\
l_{31} & l_{32} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
2 & 1 & 3 \\
0 & 3/2 & -23/2 \\
0 & 7/2 & -19/2
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
11/2 & 1 & 0 \\
9/2 & l_{32} & 1
\end{vmatrix}
$

$
U =
\begin{vmatrix}
2 & 1 & 3 \\
0 & 3/2 & -23/2 \\
0 & 0 & 52/3
\end{vmatrix}
L = 
\begin{vmatrix}
1 & 0 & 0 \\
11/2 & 1 & 0 \\
9/2 & 7/3 & 1
\end{vmatrix}
$

In [46]:
u = np.matrix([[2, 1, 3], [0, 3/2, -23/2], [0, 0, 52/3]])
l = np.matrix([[1, 0, 0], [11/2, 1, 0], [9/2, 7/3, 1]])

In [47]:
np.dot(l, u)

matrix([[ 2.,  1.,  3.],
        [11.,  7.,  5.],
        [ 9.,  8.,  4.]])

$
Ly = b \\
\begin{cases}
y_1 = 1 \\
11/2y_1 + y_2 = -6 \\
9/2y_1 + 7/3y_2 + y_3 = -5
\end{cases}
$

$y_2 = -6 - 11/2 = -23/2$

$
y_3 = -5 + 134/6 = 52/3
$

$Ux = y$

$
\begin{cases}
2x_1 + x_2 + x_3 = 1 \\
3/2x_2 - 23/2x_3 = -23/2 \\
52/3x_3 = 52/3
\end{cases}
$

$
x_3 = 1 \\
x_2 = 0 \\
x_1 = 0
$

$\begin{cases}
2x_{1}+x_{2}+3x_{3} \neq 1 \\
11x_{1}+7x_{2}+5x_{3} \neq -6 \\
9x_{1}+8x_{2}+4x_{3} \neq -5
\end{cases}$

In [57]:
import scipy.linalg

In [58]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

print(f'lu:\n{lu}\n')
print(f'piv:\n{piv}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.  0.  1.]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

lu:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

piv:
[1 2 2]



__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [59]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'K:\n{K}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

K:
(array([[  9.,  -5.,   5.],
       [-45.,   5.,   2.],
       [ 45., -15.,   3.]]), False)

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]



__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

__TIMEOUT__