## Практическое задание

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])

In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
U

matrix([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
        [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
        [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
        [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
        [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [13]:
V = W.T

In [16]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

matrix([[8.82486885, 0.        , 0.        ],
        [0.        , 6.14060608, 0.        ],
        [0.        , 0.        , 2.53271528],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]])

In [23]:
np.set_printoptions(precision=2, suppress=True)

In [24]:
np.dot(np.dot(U,D), V.T)

matrix([[ 1.,  2.,  0.],
        [ 0., -0.,  5.],
        [ 3., -4.,  2.],
        [ 1.,  6.,  5.],
        [-0.,  1.,  0.]])

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;

In [27]:
D

matrix([[8.82, 0.  , 0.  ],
        [0.  , 6.14, 0.  ],
        [0.  , 0.  , 2.53],
        [0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  ]])

$A_E = 8.82$

In [37]:
np.linalg.norm(A, ord=2)

8.824868854820444

   
    б) норму Фробениуса.

In [36]:
AF = np.sqrt(D[0,0]**2 + D[1,1]**2 + D[2,2]**2)
AF

11.045361017187261

In [38]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [39]:
np.linalg.norm(A, ord=None)

11.045361017187261